# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: LightTag - The easy way to annotate text
email: hello@lighttag.io
description: >- # this means to ignore newlines until "baseurl:"
  LightTag is the easy way to label text with a team. We provide an annotation interface,
  the infrastructure to work with multiple annotators, analytics on your project (such as inter annotator agreement)
  and the ability to upload pre-annotations to help your annotators work faster.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lighttag.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: LabeledData
logo: /assets/img/logo.png
read_time: true
mathjax: false
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
feed:
  path: atom.xml
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-twitter-plugin

# Build settings
markdown: kramdown

backend_url: https://onboarding.lighttag.io/
stripe_pkkey: pk_live_uNZmwgWUAMmyMDv5xHFKbrxG

collections:
  posts:
    permalink: /blog/:slug/
  pages:
    permalink: /blog/:basename
    url: /blog/:basename
  legal:
    output: true
  projects:
    output: true

    

site.google_analytics: UA-113289574-1

